pipeline {

    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "Building...."'
                dir('backend') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Testing...."'
                dir('backend') {
                    sh 'mvn test'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploying...."'
            }
        }
    }
}