pipeline {

    agent any

    stages {
        stage('Preprocess') {
            steps {
                sh 'cd /backend'
            }
        }
        stage('Build') {
            steps {
                sh 'echo "Building...."'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Testing...."'
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploying...."'
            }
        }
    }
}